name: Labeling closed issues
on:
  issues:
    types: ['closed']

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    if: github.repository == 'llvm/llvm-project'
    steps:
      - uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90  # 1.0.4
        with:
          remove-labels: 'awaiting-review'
